### ISSUE TITLE
File projectnya belum masuk

### ISSUE THREAD

**Issue by rrmahardhika** [Dimasariyudha/Dimas_ariyudha_Trpl5B#1]
Ini file dari projek android nya belum terinclude ke repository. Bisa di add dulu utk folder projectnya ya.
https://scribehow.com/shared/How_to_Add_Folders_to_GitHub__KBbre0tHSiqCOpzEJmW3aw

**Comment by Dimasariyudha** [comment]
baik pak terima kasih

**Comment by rrmahardhika** [comment]
Ok, closed.
